import 'prismjs/themes/prism.css'
import 'prismjs/plugins/toolbar/prism-toolbar.css'

import 'prismjs'
import 'prism-svelte'
import 'prismjs/components/prism-markdown.js'
import 'prismjs/components/prism-css.js'
import 'prismjs/plugins/toolbar/prism-toolbar.js'
import 'clipboard/dist/clipboard.js'
import 'prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard.js'
